# Generated by Django 4.0.3 on 2023-05-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwrite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ai_image',
            new_name='image',
        ),
    ]
