# Generated by Django 4.0.3 on 2023-05-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwrite', '0002_rename_ai_image_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='ai_image',
        ),
    ]
